// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimit":       schema_pkg_apis_limit_v1alpha1_ClusterLimit(ref),
		"github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitSpec":   schema_pkg_apis_limit_v1alpha1_ClusterLimitSpec(ref),
		"github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitStatus": schema_pkg_apis_limit_v1alpha1_ClusterLimitStatus(ref),
	}
}

func schema_pkg_apis_limit_v1alpha1_ClusterLimit(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterLimit is the Schema for the clusterlimits API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitSpec", "github.com/myafq/limit-operator/pkg/apis/limit/v1alpha1.ClusterLimitStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_limit_v1alpha1_ClusterLimitSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterLimitSpec defines the desired state of ClusterLimit",
				Properties: map[string]spec.Schema{
					"limitRange": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/api/core/v1.LimitRangeSpec"),
						},
					},
					"namespaceSelector": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"k8s.io/api/core/v1.LimitRangeSpec", "k8s.io/apimachinery/pkg/apis/meta/v1.LabelSelector"},
	}
}

func schema_pkg_apis_limit_v1alpha1_ClusterLimitStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ClusterLimitStatus defines the observed state of ClusterLimit",
				Properties: map[string]spec.Schema{
					"namespacesEnforced": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"namespacesEnforced"},
			},
		},
		Dependencies: []string{},
	}
}
